// <auto-generated />
using System;
using EventApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Large industry conferences and summits.",
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hands-on training workshops.",
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Live music and performances.",
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sporting events and tournaments.",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Community and networking meetups.",
                            Name = "Meetup"
                        });
                });

            modelBuilder.Entity("EventApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventDate");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Annual .NET developer conference.",
                            EventDate = new DateTime(2026, 9, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lahore",
                            Title = ".NET Conf 2026",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hands-on EF Core workshop.",
                            EventDate = new DateTime(2026, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karachi",
                            Title = "EF Core Deep Dive",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Live in concert.",
                            EventDate = new DateTime(2026, 10, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Islamabad",
                            Title = "Coldplay Live",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Annual city marathon.",
                            EventDate = new DateTime(2026, 11, 1, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lahore",
                            Title = "City Marathon",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cloud community meetup.",
                            EventDate = new DateTime(2026, 8, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karachi",
                            Title = "Azure Meetup",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Artificial intelligence summit.",
                            EventDate = new DateTime(2026, 9, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lahore",
                            Title = "AI Summit",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frontend workshop.",
                            EventDate = new DateTime(2026, 10, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Islamabad",
                            Title = "React Workshop",
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An evening of jazz.",
                            EventDate = new DateTime(2026, 11, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lahore",
                            Title = "Jazz Night",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "National cricket finals.",
                            EventDate = new DateTime(2026, 12, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karachi",
                            Title = "Cricket Finals",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Founders networking meetup.",
                            EventDate = new DateTime(2026, 8, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Islamabad",
                            Title = "Startup Meetup",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EventApi.Models.EventBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventBookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedAt = new DateTime(2026, 7, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Status = "Confirmed",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookedAt = new DateTime(2026, 7, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Status = "Pending",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookedAt = new DateTime(2026, 7, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Status = "Confirmed",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookedAt = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 5,
                            Status = "Cancelled",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            BookedAt = new DateTime(2026, 7, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 9,
                            Status = "Confirmed",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EventApi.Models.EventFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FavoritedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventFavorites");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            EventId = 1,
                            FavoritedAt = new DateTime(2026, 7, 6, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            EventId = 6,
                            FavoritedAt = new DateTime(2026, 7, 6, 10, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            EventId = 3,
                            FavoritedAt = new DateTime(2026, 7, 7, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            EventId = 7,
                            FavoritedAt = new DateTime(2026, 7, 7, 9, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 1,
                            EventId = 9,
                            FavoritedAt = new DateTime(2026, 7, 8, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EventApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@eventboard.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = "$2a$11$ExjLvV2ie52b756HbndsOOLDoKEexPRtc9Sz7oxFigjZSGtiAaMA2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara@eventboard.com",
                            IsActive = true,
                            Name = "Sara Khan",
                            PasswordHash = "$2a$11$B6Ctfp3GjbtOj8ZfvmiLtuQwnBvys/603hpg4OA36745T.AYNx.Qa",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bilal@eventboard.com",
                            IsActive = true,
                            Name = "Bilal Ahmed",
                            PasswordHash = "$2a$11$mWlv.Rm30KrmZJR88vNNiew809Api5AXDNWBgRlooYEL6nnASB1m.",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("EventApi.Models.Event", b =>
                {
                    b.HasOne("EventApi.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventApi.Models.EventBooking", b =>
                {
                    b.HasOne("EventApi.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventApi.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventApi.Models.EventFavorite", b =>
                {
                    b.HasOne("EventApi.Models.Event", "Event")
                        .WithMany("Favorites")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventApi.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventApi.Models.Event", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("EventApi.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
